### ISSUE TITLE
Read credentials from env vars or SSM parameter store

### ISSUE THREAD

**Issue by evandam** [bdudelsack/docker-registry-mirror#1]
Hi @bdudelsack,

I was wondering if there's a way to read credentials from an external source, either environment variables or something like SSM parameter store to avoid hardcoding credentials in the config.yaml.

It would be great if we were able to pass something like `QUAY_IO_USERNAME` and `QUAY_IO_PASSWORD`.

Thanks!

**Comment by bdudelsack** [comment]
Hello @evandam,

i could implement expanding of environment variabliabes in the config file, so you coud do something like this:

```yaml
auth:
  registry.example.com:
    username: ${MY_USERNAME}
    password: ${MY_PASSWORD}
```
Would this be the solution for you?

**Comment by evandam** [comment]
I think that would be a great solution! Although unfortunately I noticed a larger problem for me where images pushed to Quay.io are not appearing. I was using a config like this:

```yaml
repositories:
  - source: library/ruby
    destination: quay.io/myorg/ruby
    matches:
      - ^2.5.8$
 auth:
  quay.io:
    username: ${QUAY_USERNAME}
    password: ${QUAY_PASSWORD}
```

docker-registry-mirror reports that it ran successfully, but nothing shows on Quay's side.
